pub mod core;
pub mod protocols;
pub mod composition;
pub mod advanced;
pub mod constructions;
pub mod batch;
pub mod utils;

pub use core::curve::{
    validate_point,
    reject_identity,
    point_coordinates,
    point_x,
    point_y,
};

pub use core::encoding::{
    append_scalar,
    append_point,
    append_point_xy,
    encode_scalar,
    encode_point,
    encode_point_xy,
};

pub use core::canonical::{
    TAG_SCHNORR,
    TAG_DLOG,
    TAG_CHAUM_PED,
    TAG_OKAMOTO,
    TAG_PEDERSEN,
    TAG_PEDERSEN_EQ,
    TAG_PEDERSEN_RERAND,
    OkamotoStatementDecoded,
    OkamotoProofDecoded,
    RingStatementDecoded,
    RingProofDecoded,
    OneOutOfManyStatementDecoded,
    OneOutOfManyProofDecoded,
    DecodedSigmaStatement,
    DecodedSigmaProof,
    encode_schnorr_statement,
    encode_dlog_statement,
    encode_chaum_ped_statement,
    encode_okamoto_statement,
    encode_pedersen_statement,
    encode_pedersen_eq_statement,
    encode_pedersen_rerand_statement,
    encode_sigma_statement,
    encode_one_out_of_many_statement,
    encode_one_out_of_many_proof,
    encode_schnorr_commitment,
    encode_dlog_commitment,
    encode_chaum_ped_commitment,
    encode_okamoto_commitment,
    encode_pedersen_commitment,
    encode_pedersen_eq_commitment,
    encode_pedersen_rerand_commitment,
    encode_sigma_commitment,
    encode_schnorr_proof,
    encode_dlog_proof,
    encode_chaum_ped_proof,
    encode_okamoto_proof,
    encode_pedersen_proof,
    encode_pedersen_eq_proof,
    encode_pedersen_rerand_proof,
    encode_sigma_proof,
    decode_schnorr_statement,
    decode_dlog_statement,
    decode_chaum_ped_statement,
    decode_okamoto_statement,
    decode_pedersen_statement,
    decode_pedersen_eq_statement,
    decode_pedersen_rerand_statement,
    decode_sigma_statement,
    decode_schnorr_statement_strict,
    decode_dlog_statement_strict,
    decode_chaum_ped_statement_strict,
    decode_okamoto_statement_strict,
    decode_pedersen_statement_strict,
    decode_pedersen_eq_statement_strict,
    decode_pedersen_rerand_statement_strict,
    decode_sigma_statement_strict,
    decode_one_out_of_many_statement,
    decode_one_out_of_many_statement_strict,
    decode_schnorr_commitment,
    decode_dlog_commitment,
    decode_chaum_ped_commitment,
    decode_okamoto_commitment,
    decode_pedersen_commitment,
    decode_pedersen_eq_commitment,
    decode_pedersen_rerand_commitment,
    decode_schnorr_commitment_strict,
    decode_dlog_commitment_strict,
    decode_chaum_ped_commitment_strict,
    decode_okamoto_commitment_strict,
    decode_pedersen_commitment_strict,
    decode_pedersen_eq_commitment_strict,
    decode_pedersen_rerand_commitment_strict,
    decode_schnorr_proof,
    decode_dlog_proof,
    decode_chaum_ped_proof,
    decode_okamoto_proof,
    decode_pedersen_proof,
    decode_pedersen_eq_proof,
    decode_pedersen_rerand_proof,
    decode_sigma_proof,
    decode_schnorr_proof_strict,
    decode_dlog_proof_strict,
    decode_chaum_ped_proof_strict,
    decode_okamoto_proof_strict,
    decode_pedersen_proof_strict,
    decode_pedersen_eq_proof_strict,
    decode_pedersen_rerand_proof_strict,
    decode_sigma_proof_strict,
    decode_one_out_of_many_proof,
    decode_one_out_of_many_proof_strict,
    encode_ring_statement,
    encode_ring_commitment,
    encode_ring_proof,
    decode_ring_statement,
    decode_ring_statement_strict,
    decode_ring_commitment,
    decode_ring_commitment_strict,
    decode_ring_proof,
    decode_ring_proof_strict,
};

pub use core::scalar::{
    is_nonzero_scalar,
    is_canonical_scalar,
    order_u256,
    reduce_mod_order,
};
pub use core::challenge::{compute_challenge, compute_challenge_checked, validate_challenge};
pub use core::sigma::{
    absorb_statement,
    absorb_commitment,
    validate_statement_and_proof,
    verify_with_challenge,
    derive_challenge,
    verify_batchable,
};

pub use core::errors::{VerifyError, VerifyResult};

pub use core::limits::{
    MAX_OKAMOTO_BASES,
    MAX_OKAMOTO_BASES_U256,
    MAX_RING_SIZE,
    MAX_RING_SIZE_U256,
    MAX_ONE_OUT_OF_MANY,
    MAX_ONE_OUT_OF_MANY_U256,
};

pub use protocols::pedersen::bases::{
    PEDERSEN_H_DOMAIN,
    PEDERSEN_H_COUNTER,
    PEDERSEN_H_X,
    PEDERSEN_H_Y,
    pedersen_h,
};

pub use protocols::{
    atomic::dlog::verify_dlog,
    atomic::dlog::verify_dlog_short,
    atomic::dlog::verify_dlog_bytes,
    atomic::dlog::verify_dlog_short_bytes,
    atomic::schnorr::verify_schnorr,
    atomic::schnorr::verify_schnorr_short,
    atomic::schnorr::verify_schnorr_bytes,
    atomic::schnorr::verify_schnorr_short_bytes,
    atomic::chaum_pedersen::verify_chaum_ped,
    atomic::chaum_pedersen::verify_chaum_ped_short,
    atomic::chaum_pedersen::verify_chaum_ped_bytes,
    atomic::chaum_pedersen::verify_chaum_ped_short_bytes,
    atomic::okamoto::verify_okamoto,
    atomic::okamoto::verify_okamoto_short,
    atomic::okamoto::verify_okamoto_bytes,
    atomic::okamoto::verify_okamoto_short_bytes,
    pedersen::opening::verify_pedersen_opening,
    pedersen::opening::verify_pedersen_opening_short,
    pedersen::opening::verify_pedersen_opening_bytes,
    pedersen::opening::verify_pedersen_opening_short_bytes,
    pedersen::equality::verify_pedersen_eq,
    pedersen::equality::verify_pedersen_eq_short,
    pedersen::equality::verify_pedersen_eq_bytes,
    pedersen::equality::verify_pedersen_eq_short_bytes,
    pedersen::rerand::verify_pedersen_rerand,
    pedersen::rerand::verify_pedersen_rerand_short,
    pedersen::rerand::verify_pedersen_rerand_bytes,
    pedersen::rerand::verify_pedersen_rerand_short_bytes,
};

pub use protocols::types::{
    SchnorrStatement,
    SchnorrProof,
    DLogStatement,
    DLogProof,
    ChaumPedStatement,
    ChaumPedProof,
    OkamotoStatement,
    OkamotoProof,
    PedersenStatement,
    PedersenProof,
    PedersenEqStatement,
    PedersenEqProof,
    PedersenRerandStatement,
    PedersenRerandProof,
    SigmaStatement,
    SigmaProof,
};

pub use composition::{
    AndInstance,
    OrInstance,
    verify_and,
    verify_or,
    verify_and_bytes,
    verify_or_bytes,
};

pub use advanced::ring::{RingStatement, RingProof, verify_ring};
pub use advanced::ring::verify_ring_bytes;

pub use core::transcript::{
    CURVE_ID_STARK,
    PROTOCOL_SCHNORR,
    PROTOCOL_DLOG,
    PROTOCOL_CHAUM_PED,
    PROTOCOL_OKAMOTO,
    PROTOCOL_PEDERSEN,
    PROTOCOL_PEDERSEN_EQ,
    PROTOCOL_PEDERSEN_RERAND,
    PROTOCOL_ONE_OUT_OF_MANY,
    PROTOCOL_AND,
    PROTOCOL_OR,
    PROTOCOL_RING,
    PROTOCOL_BATCH,
    Transcript,
    transcript_new_schnorr,
    transcript_new_dlog,
    transcript_new_chaum_ped,
    transcript_new_okamoto,
    transcript_new_pedersen,
    transcript_new_pedersen_eq,
    transcript_new_pedersen_rerand,
    transcript_new_and,
    transcript_new_or,
    transcript_new_ring,
    transcript_new_batch,
    transcript_new_one_out_of_many,
    build_schnorr_transcript,
    build_dlog_transcript,
    build_chaum_ped_transcript,
    build_okamoto_transcript,
    build_pedersen_transcript,
    build_pedersen_eq_transcript,
    build_pedersen_rerand_transcript,
    build_ring_transcript,
    transcript_append_felt,
    transcript_append_span,
    transcript_append_scalar,
    transcript_append_point,
    transcript_append_point_xy,
    transcript_hash,
    transcript_challenge,
};

pub use advanced::one_out_of_many::{
    PedersenOneOutOfManyStatement,
    PedersenOneOutOfManyProof,
    verify_pedersen_one_out_of_many,
    verify_pedersen_one_out_of_many_bytes,
    OOM_GK_COMMITMENT_BLOCKS_PER_BIT,
    OOM_GK_SCALAR_BLOCKS_PER_BIT,
};

pub use composition::{
    batch_verify_schnorr,
    batch_verify_dlog,
    batch_verify_chaum_ped,
    batch_verify_okamoto,
    batch_verify_pedersen,
    batch_verify_pedersen_eq,
    batch_verify_pedersen_rerand,
    batch_verify_schnorr_bytes,
    batch_verify_dlog_bytes,
    batch_verify_chaum_ped_bytes,
    batch_verify_okamoto_bytes,
    batch_verify_pedersen_bytes,
    batch_verify_pedersen_eq_bytes,
    batch_verify_pedersen_rerand_bytes,
};

pub use utils::bytes::{
    SCALAR_BYTES,
    POINT_BYTES,
    decode_scalar_be32,
    decode_point_be64,
    decode_scalars_be32,
    decode_points_be64,
};

#[cfg(test)]
mod tests;
